# azure-pipelines.yml

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      containerRegistry: 'acrConnection'  # Specify the name of your Azure Container Registry service connection
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'

  - task: Docker@2
    displayName: 'Push Docker Image to Registry'
    inputs:
      containerRegistry: 'acrConnection'  # Specify the name of your Azure Container Registry service connection
      repository: 'your-acr-name.azurecr.io/your-docker-image'  # Replace with your Azure Container Registry name and image name
      command: 'push'
      tags: 'latest'
