# azure-pipelines.yml

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Login to Azure Container Registry'
    inputs:
      containerRegistry: 'acrConnection'  # Specify the name of your Azure Container Registry service connection
      command: 'login'

  - task: Docker@2
    displayName: 'Tag Docker Image'
    inputs:
      containerRegistry: 'acrConnection'  # Specify the name of your Azure Container Registry service connection
      repository: 'your-acr-name.azurecr.io/your-docker-image'  # Replace with your Azure Container Registry name and image name
      command: 'tag'
      arguments: 'local-docker-image:latest your-acr-name.azurecr.io/your-docker-image:latest'

  - task: Docker@2
    displayName: 'Push Docker Image to Registry'
    inputs:
      containerRegistry: 'acrConnection'  # Specify the name of your Azure Container Registry service connection
      repository: 'your-acr-name.azurecr.io/your-docker-image'  # Replace with your Azure Container Registry name and image name
      command: 'push'
      tags: 'latest'

- job: Deploy
  displayName: 'Deploy Docker Image'
  dependsOn: Build
  steps:
  # Steps for deploying to Azure services typically involve using Azure-specific tasks or scripts. The example provided uses SSH, which is not typically used for Azure deployments.
